version: '3.9'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: umrobotics/slam:latest
    entrypoint: /bin/zsh
    command: roscore
    networks:
      - ros
    restart: always


  slam:
    image: umrobotics/slam:latest
    depends_on:
      - ros-master
    container_name: slam
    networks:
      - ros
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_GRAPHICSSYSTEM=native"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "TERM=xterm-256color"
      - "XAUTHORITY"
    working_dir: "/root/ws/"
    privileged: true
    devices:
      - /dev/nvidia0
      - /dev/nvidia-modeset
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .zshrc:/root/.zshrc:rw
      - .zsh_history:/root/.zsh_history:rw
      - /home/$USER/Projects/curly/:/root/ws/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: /bin/zsh
